### ISSUE TITLE
Crash when tracking screen on iOS

### ISSUE THREAD

**Issue by mininao** [BonifyByForteil/react-native-piwik#1]
After a fresh install and following the instructions for Android and iOS, the library works perfectly well for Android but crashes in iOS with the following error : 
![Screenshot ios](https://cloud.githubusercontent.com/assets/5511564/24145788/12a27cfe-0e33-11e7-97c6-f9dedc8da607.png)
```
Exception 'CoreData: Cannot load NSManagedObjectModel.  
nil is an illegal URL parameter' was thrown while invoking trackScreen on target Piwik with params
[...]
```

I suspect this is an issue around these lines https://github.com/BonifyByForteil/react-native-piwik/blob/master/ios/PiwikTracker/PiwikTracker.m#L1568, where `URLForResource` fails to find the model

Unfortunately I have zero objective-c experience so I don't exactly grasp how to fix this.

If that can help, the source code for my project is available at https://github.com/BDE-ESIEE/mobile

Anyway, thanks a bunch for this very useful module 😉 !

**Comment by ruiaraujo** [comment]
This is caused by Xcode not copying the Core data file. Expand the BNFPiwik.xcodeproj project and drag the piwiktracker v2.xcdatamodel file inside PiwikTracker to your Project.

See if that helps.

**Comment by i-tu** [comment]
I can confirm that @ruiaraujo 's solution works.

This worked for me: Drag `node_modules/react-native-piwik/ios/PiwikTracker/piwiktracker.xcdatamodeld` into the xcode project navigator, and uncheck "copy" when presented a dialog.

I put mine into the folder containing AppDelegate.m, etc.

**Comment by coldbess** [comment]
maybe modify README.md
####iOS

1.Add node_modules/react-native-piwik/ios/BNFPiwik.xcodeproj to your xcode project, usually under the Libraries group
2.Add libBNFPiwik.a (from Products under BNFPiwik.xcodeproj) to build target's Linked Frameworks and Libraries list
3.Delete piwiktracker.xcdatamodeld(from Libraries under BNFPiwik.xcodeproj/PiwikTracker)
4.Drag node_modules/react-native-piwik/ios/PiwikTracker/piwiktracker.xcdatamodeld into the folder containing AppDelegate.m

if you don't delete piwiktracker.xcdatamodeld(from Libraries) , your siteId is not corrent

**Comment by diedsmiling** [comment]
Updated README.md. Thanks for feedback!
