### ISSUE TITLE
How to set Site_Id with tracker 

### ISSUE THREAD

**Issue by EyalAlbilia** [BonifyByForteil/react-native-piwik#3]
this is ho it's done on web...
 _paq.push(['setSiteId', '3']);

this is the configuration for shared piwik instance in ios sdk : 
PiwikTracker.configureSharedInstance(withSiteID: "5", ...)
how to implement same functionality in plugin ?

**Comment by ruiaraujo** [comment]
Do you want to change the ID after configuring the tracker?

If you don't it is a matter of doing:
```Piwik.initTracker("https://your-piwik-domain.tld/piwik.php", 3)```

**Comment by EyalAlbilia** [comment]
thanks , i opened the ios source and saw it, but tnx again for the quick answer
