### ISSUE TITLE
undefined is not an object (evaluating 'Piwik.initTracker')

### ISSUE THREAD

**Issue by alelfreitas** [BonifyByForteil/react-native-piwik#4]
New on react-native, when I run-android this is the error screen:

![screenshot_2017-08-31-12-19-52](https://user-images.githubusercontent.com/6798273/29931221-f928247e-8e46-11e7-99ba-a86cd54f1307.png)

Follow the steps of instalation screen.

Don't have getPackages method on MainApplication.java

On the index.js I do 'import Piwik from 'react-native-piwik';' and call the initTracker on componentDidMount().

The line off the error is on 'react-native-piwik/index.js line 3:
'initTracker: Piwik.initTracker,'

I think that I'm doing something wrong.. Can you post a example project already configured?
Thanks! 

Keep the good work!

**Comment by alelfreitas** [comment]
Here, they made it a framework for react-native. And it is different from normal... Think that this is the thing.
THe getPackages function is inside a closed file called when react-native starts, so I can't change it.

**Comment by diedsmiling** [comment]
Have you followed the steps described [here](https://github.com/BonifyByForteil/react-native-piwik#android)?

**Comment by alelfreitas** [comment]
Hi!
Thanks for the aswer! Yes.. Followed the steps.. I think the problem is with the framework created by the company here... They have control of the external library and the MainApplication is created by then. So the one that is in my project make reference to the one they created.
This is why I haven't a "getPackages".

Without the "new PiwikPackage" the tracker can't be found.

This is what I think...

I'm trying to convince then to allow me to use external libraries.. I'll keep you informed.

**Comment by diedsmiling** [comment]
Ok, thanks. I will close the ticket in that case, but if you figure out that the problem is on our side I will reopen it again.
