### ISSUE TITLE
Feature Request: App-level opt-out

### ISSUE THREAD

**Issue by flindenberg** [BonifyByForteil/react-native-piwik#6]
Thank you very much for introducing piwik to react-native. Your efforts are highly appreciated. 

I was wondering whether you are planning to support app-level opt-out in the near future? 
For reference, please see the documentation of the [iOS SDK](https://github.com/piwik/piwik-sdk-android/wiki/Design-document#15-app-level-opt-out) and [Android SDK](https://github.com/piwik/piwik-sdk-ios#optout), respectively. 

Allowing the user to opt-out of the piwik tracking is a strict requirement for any app that needs to comply with the German Federal Privacy Act (BDSG).

**Comment by diedsmiling** [comment]
Hello! 
Thanks for pointing this out, it's really a good feature to have and most probably we will implement it, but right now it's hard to estimate when. Nevertheless, a PR is always welcome :)

**Comment by leoschweizer** [comment]
@diedsmiling @ruiaraujo are you planning to publish a new version to npm so this can be used via dependency management?

**Comment by diedsmiling** [comment]
@leoschweizer done. Cheers!
