### ISSUE TITLE
app crashes while tracking screen

### ISSUE THREAD

**Issue by yogeshmoradiya121** [BonifyByForteil/react-native-piwik#8]
index.ios.bundle:13081 Exception 'CoreData: Cannot load NSManagedObjectModel.  nil is an illegal URL parameter' was thrown while invoking trackScreen on target Piwik with params (
    screen,
    contact
)

**Comment by diedsmiling** [comment]
Hi! 
Can you please provide more details, so we can reproduce this error?

**Comment by diedsmiling** [comment]
I am closing this issue because could not reproduce the problem, and provided information is not enough. Once you can elaborate more on this problem issue will be open again :)
